**关于北邮校园网登录程序**

>* 这个不是破解认证。仅仅是自动认证。。
>* 目前支持的热点。。 学十宿舍网  bupt2校内网
>* 环境为 ubuntu 12.10  
>* 程序在[这里](https://gist.github.com/xiyoulaoyuanjia/2d63e1b41ec711f8d5e1)


**关于 自动登录**

这个使用了 request 相对而言比较简单。。仅仅是把密码 进行了 md5 的加密转换成16进制输出

例如如果想计算自己密码的 加密之后的密文可以按如下操作

    >>> import hashlib
    >>> hashlib.md5("124").hexdigest()
    'c8ffe9a587b126f152ed3d89a146b445'
    >>> 

**如何做到每次热点接入后自动认证呢？**

之前考虑 直接调用 NetworkManager Api [这里](http://projects.gnome.org/NetworkManager/)  操作 
当然这样可以做的事情就比较多了。。而且还看了 python 的[demo](http://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/examples/python) 
感激非常的棒

后来 在网上看到 这个[资料](http://t.du9l.com/post/40) 觉得不错。。 这里感谢这个作者
后来就直接拿过来用了。。至少现在可以满足我的要求。

>* 下载下来放到 /etc/NetworkManager/dispatcher.d/ 中
>* 注意修改可执行文件


**关于登录成功的窗口通知**

本想着这个可能十分简单的事情。。谁知道 确实花费时间最多的。。

“问题是我需要执行的脚本会执行 。。但是里面的 zenity弹出框怎么也不出来。。
为了排除是python的脚本问题。。我直接把命令放在了shell里面。也还是没有结果。。。。 
我已经查看了 networking 的日志  

nm-dispatcher.action: Script  exited with error status 1”`

后来在以为邮件列表中的网友的帮助下。。

修改了之前的程序。。
方法如下:

>* 增加环境变量
    
    export DISPLAY=:0 

>* 增加 对 x的访问权限
    
    xhost local: 1>/dev/null

这里参考了一些资料

[xhost](http://www.leidinger.net/X/xhost.html)

[cannot-open-display-problem](http://promberger.info/linux/2009/01/02/running-x-apps-like-zenity-from-crontab-solving-cannot-open-display-problem/)

算是解决了吧。。如下图

![](http://openapi.vdisk.me/?m=file&a=download_share_file&ss=b3d344--2FxLktIPmUVQn6KtbjbBClvLBx2AMZ3tC--2Blw2c--2Fhq2bVDo7GgYdp7fLKwJNg7K2wEOGfPqP9dHVWL0WzujDdvEZ)

对于 第二个有一个小问题。。现在是把上述命令放在了 startup application(ubuntu) 中 每次开机都需要运行上述命令。。
这个不能记录更改操作吗？  好吧。。这个先留着。。。

**关于bupt2校内网**

这个是最简单的。但也是花费我时间最长的一个。。



之前一直是用 python的requests 库做的。。

测试requests 如下:

    >>> requests.post(url,data={"PtUser":111,"PtPwd":33})
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 354, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 460, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 246, in send
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.8.128.1', port=80): Max retries exceeded with url: /portal/logon.cgi (Caused by <class 'httplib.BadStatusLine'>: '')
    >>> 
     
于是顺着 Caused by <class 'httplib.BadStatusLine'>: 错误 

    exception httplib.BadStatusLine
    A subclass of HTTPException. Raised if a server responds with a HTTP status code that we don’t understand.
 
以为是服务器发送了不认识的状态吗 的思路考虑 以为是服务器block 爬虫..后来各种header 各种 UA 尝试均不成功

不行，后来用 wget测试如下 
  
    wget --post-data "PtUser=111&PtPwd=33" --header="User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31" --header="Referer: http://10.8.128.1/portal/logon.cgi?userip=10.8.160.134&userurl=687474703a2f2f31302e332e382e323131" --header="Cookie: LPTSRVID=1202120206; lang=0" --header="Origin: http://10.8.128.1" --header="Host: 10.8.128.1"   http://10.8.128.1/portal/logon.cgi 
      
       
    Connecting to 10.8.128.1:80... connected. 
    HTTP request sent, awaiting response... No data received. 
    Retrying. 
      
    --2013-04-19 10:21:44--  (try: 2)  http://10.8.128.1/portal/logon.cgi 
    Connecting to 10.8.128.1:80... connected. 
    HTTP request sent, awaiting response... No data received. 
    Retrying. 

才发现是服务器端没有回应。。。

于是从新从chrome 看post 数据。。终于。。发现 post 少传了一个参数 PtButton 导致。。。唉。。。

修改之后终于完美got it







